version: 2.1

orbs:
  cypress: cypress-io/cypress@2.0.0

workflows:
  run_cypress_tests:
    jobs:
      - cypress/run:
          filters:
            branches:
            pull_requests:
              branches:
                - '*' # Run on all branches 
                